
server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

#  spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name
#  spring.datasource.username=root
#  spring.datasource.password=your_password
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true


  datasource:
    url: jdbc:mysql://localhost:3306/task_user_service
    username: root
    password: Dishu@2010
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/